### ISSUE TITLE
Regarding TextArea 

### ISSUE THREAD

**Issue by jhaji0675** [ShubhInfotech-Bhilai/MyRepo#1]
Hello Sir ! Hope you are Well and Safe . I am an employee of Tata ELxsi.

Just few weeks back you trained us on Qt/Qml . 

So Just had some doubts regarding Textarea . Please try to help me .
 Actually the issue is that I have a Textarea inside a rectangle of fixed width & height 288 and 78 respectively and the text inside Textarea has line-height of 22px . So I am in a trouble of how to do that ? Even I tried may things but still no success .

So please try to help me out. 
[TestBox.zip](https://github.com/ShubhInfotech-Bhilai/MyRepo/files/6481842/TestBox.zip)
Here is the image folder  for your convinience.

[textarea images.zip](https://github.com/ShubhInfotech-Bhilai/MyRepo/files/6482130/textarea.images.zip)

You can even contact me here if possible.
Mob:- 9620564905
email - mayankjha4318@gmail.com

**Comment by Subhash-Pal** [comment]
Sure mayank,will do that.
